name: tests
on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/lint.yml'
      - '**.py'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --progress-bar off --upgrade pip setuptools
          pip install --progress-bar off .
          pip install --progress-bar off flake8 black isort mypy
      - run: flake8 . --show-source
      - run: black --check --diff .
      - run: isort --check --diff .
      - run: mypy .
